import { RULE_HIDDEN_CLASS } from '../constants';
import { rootThemeCssRules } from '../settings/defaults';

/**
 * Injected once at init. Class prefix: `bss-toolkit-`.
 *
 * Kept as a JS string (not an imported `.css` file) on purpose: the rules include
 * Battlemetrics' generated emotion classes (`css-*`), `!important`, and units like
 * `100vw`/`100pt` that a CSS minifier could mangle or drop. Building the `<style>`
 * text in JS guarantees byte-identical output.
 */
export const CssInjector = {
  injected: false,

  buildRules(): string[] {
    return [
      ...rootThemeCssRules(),
      // -- Server identity chrome (left bar + known-server H1 pill) --
      'html.bss-toolkit-has-server-accent::before {',
      "  content: '';",
      '  position: fixed;',
      '  top: 0;',
      '  left: 0;',
      '  bottom: 0;',
      '  width: 4px;',
      '  background: var(--bss-server-accent, #64748b);',
      '  z-index: 99999;',
      '  pointer-events: none;',
      '}',
      '.bss-toolkit-server-h1-with-pill {',
      '  display: flex;',
      '  align-items: center;',
      '  flex-wrap: wrap;',
      '  column-gap: 10px;',
      '  row-gap: 6px;',
      '}',
      '.bss-toolkit-server-pill {',
      '  display: inline-flex;',
      '  align-items: center;',
      '  flex-shrink: 0;',
      '  border-radius: 999px;',
      '  padding: 2px 10px;',
      '  font-size: 12px;',
      '  font-weight: 700;',
      '  letter-spacing: 0.02em;',
      '  line-height: 1.3;',
      '  color: var(--bss-server-accent, #64748b);',
      '  border: 1px solid var(--bss-server-accent, #64748b);',
      '  background: rgba(15, 23, 42, 0.55);',
      '  vertical-align: middle;',
      '}',

      // -- Shared buttons --
      '.bss-toolkit-btn {',
      '  background: #243044;',
      '  color: #e8edf5;',
      '  border: 1px solid #3a4a62;',
      '  border-radius: 6px;',
      '  padding: 4px 8px;',
      '  cursor: pointer;',
      '  font-size: 12px;',
      '}',
      '.bss-toolkit-btn:hover { background: #2c3a50; }',

      // -- Player list name column (block flow: name+chip on line 1, details line 2) --
      '.bss-toolkit-name-row { display: block; }',
      '.bss-toolkit-name-row > a { display: inline; vertical-align: baseline; }',

      // -- CBL reputation chip --
      '.bss-toolkit-cbl-wrap {',
      '  display: inline-flex;',
      '  align-items: center;',
      '  gap: 4px;',
      '  margin: 0 0 0 8px;',
      '  vertical-align: middle;',
      '  max-width: 100%;',
      '}',
      '.bss-toolkit-cbl-chip {',
      '  display: inline-flex;',
      '  align-items: center;',
      '  gap: 4px;',
      '  border-radius: 999px;',
      '  padding: 3px 10px;',
      '  font-size: 11px;',
      '  font-weight: 700;',
      '  border: 1px solid rgba(255,255,255,.22);',
      '  text-decoration: none;',
      '  cursor: pointer;',
      '  line-height: 1.25;',
      '  box-shadow: 0 1px 2px rgba(0,0,0,.35);',
      '}',
      '.bss-toolkit-cbl-chip:hover { filter: brightness(1.08); }',
      '.bss-toolkit-cbl-chip--muted { opacity: .85; font-weight: 500; }',
      '.bss-toolkit-cbl-chip--err {',
      '  border-color: #6b3a3a;',
      '  background: #2a1818;',
      '  color: #ffb4b4;',
      '}',

      // -- Filters (dim/hide non-matching rows or feed lines) --
      '.bss-toolkit-player-filtered, .' + RULE_HIDDEN_CLASS + ' { display: none !important; }',
      '.bss-toolkit-feed-filtered { opacity: .22; }',

      // -- Feed highlight rules (left border + faint background) --
      '.bss-toolkit-feed-warn {',
      '  box-shadow: inset 3px 0 0 var(--bss-hl-warn) !important;',
      '  background: color-mix(in srgb, var(--bss-hl-warn) 8%, transparent) !important;',
      '}',
      '.bss-toolkit-feed-trigger {',
      '  box-shadow: inset 3px 0 0 var(--bss-hl-trigger) !important;',
      '  background: color-mix(in srgb, var(--bss-hl-trigger) 7%, transparent) !important;',
      '}',
      '.bss-toolkit-feed-kick {',
      '  box-shadow: inset 3px 0 0 var(--bss-hl-kick) !important;',
      '  background: color-mix(in srgb, var(--bss-hl-kick) 8%, transparent) !important;',
      '}',

      // -- Admin tag: cyan player name (BM admin badge present) --
      '.bss-toolkit-admin-tag-name { color: var(--bss-admin-tag) !important; }',

      // -- Player row flag tints (priority: admin → problem player → sus → steam ban) --
      '.bss-toolkit-player-accent { border-left: 3px solid transparent; }',
      '.bss-toolkit-bmflag-admin {',
      '  border-left: 3px solid var(--bss-flag-admin) !important;',
      '  background: color-mix(in srgb, var(--bss-flag-admin) 12%, transparent) !important;',
      '}',
      '.bss-toolkit-bmflag-problem {',
      '  border-left: 3px solid var(--bss-flag-problem) !important;',
      '  background: color-mix(in srgb, var(--bss-flag-problem) 14%, transparent) !important;',
      '}',
      '.bss-toolkit-bmflag-sus {',
      '  border-left: 3px solid var(--bss-flag-sus) !important;',
      '  background: color-mix(in srgb, var(--bss-flag-sus) 12%, transparent) !important;',
      '}',
      '.bss-toolkit-bmflag-steam-ban {',
      '  border-left: 3px solid var(--bss-flag-steam-ban) !important;',
      '  background: color-mix(in srgb, var(--bss-flag-steam-ban) 14%, transparent) !important;',
      '}',

      // -- Player list: slightly smaller CBL chip --
      'div[data-session] .bss-toolkit-cbl-chip--table {',
      '  font-size: 9.9px;',
      '  padding: 2.7px 9px;',
      '  gap: 3.6px;',
      '}',
      'div[data-session] .bss-toolkit-cbl-wrap { margin-left: 7.2px; }',

      // -- Profile header CBL chip beside h1 --
      '.bss-toolkit-profile-h1-with-chip {',
      '  display: flex;',
      '  align-items: center;',
      '  flex-wrap: wrap;',
      '  column-gap: 10px;',
      '  row-gap: 6px;',
      '}',
      '.bss-toolkit-cbl-wrap--profile-header {',
      '  margin: 0 !important;',
      '  vertical-align: middle;',
      '}',

      // -- Profile Overview: Copy + Note Menu --
      '.bss-toolkit-profile-actions {',
      '  display: flex;',
      '  flex-direction: column;',
      '  gap: 8px;',
      '  margin: 10px 0 16px 0;',
      '  max-width: 260px;',
      '  font-family: system-ui, -apple-system, Segoe UI, Roboto, sans-serif;',
      '}',
      '.bss-toolkit-profile-actions .bss-toolkit-btn--block {',
      '  display: block;',
      '  width: 100%;',
      '  padding: 9px 12px;',
      '  font-size: 13px;',
      '  font-weight: 600;',
      '  text-align: center;',
      '  box-sizing: border-box;',
      '}',
      '.bss-toolkit-profile-actions .bss-toolkit-btn--primary {',
      '  background: #1e3a5f;',
      '  border-color: #3b82f6;',
      '  color: #e8edf5;',
      '}',
      '.bss-toolkit-profile-actions .bss-toolkit-btn--primary:hover { background: #234878; }',
      '.bss-toolkit-profile-actions .bss-toolkit-btn--copied {',
      '  border-color: #3d8f5c !important;',
      '  background: #1a3d2e !important;',
      '}',
      '.bss-toolkit-note-menu { position: relative; width: 100%; }',
      '.bss-toolkit-note-dropdown {',
      '  display: none;',
      '  background: #0e131a;',
      '  border: 1px solid #2a3340;',
      '  border-radius: 6px;',
      '  margin-top: 4px;',
      '  overflow: hidden;',
      '}',
      '.bss-toolkit-note-dropdown.is-open { display: block; }',
      '.bss-toolkit-note-dropdown button {',
      '  display: block;',
      '  width: 100%;',
      '  text-align: left;',
      '  padding: 8px 10px;',
      '  background: transparent;',
      '  border: none;',
      '  border-bottom: 1px solid #1f2937;',
      '  color: #e8edf5;',
      '  cursor: pointer;',
      '  font-size: 12px;',
      '}',
      '.bss-toolkit-note-dropdown button:last-child { border-bottom: none; }',
      '.bss-toolkit-note-dropdown button:hover { background: #243044; }',
      '.bss-toolkit-note-submenu { display: none; margin-top: 4px; }',
      '.bss-toolkit-note-submenu.is-open { display: block; }',

      // -- Settings gear + popout (owned overlay; not a BM modal) --
      '.bss-toolkit-settings-gear {',
      '  position: fixed;',
      '  left: 12px;',
      '  bottom: 16px;',
      '  z-index: 100000;',
      '  width: 36px;',
      '  height: 36px;',
      '  display: flex;',
      '  align-items: center;',
      '  justify-content: center;',
      '  border-radius: 10px;',
      '  border: 1px solid #3a4a62;',
      '  background: #161b22;',
      '  color: #9aa7b8;',
      '  cursor: pointer;',
      '  box-shadow: 0 4px 16px rgba(0,0,0,.4);',
      '  padding: 0;',
      '}',
      '.bss-toolkit-settings-gear:hover, .bss-toolkit-settings-gear[aria-expanded="true"] {',
      '  color: #e8edf5;',
      '  border-color: #4a8dfa;',
      '  background: #1c2430;',
      '}',
      '.bss-toolkit-settings-panel {',
      '  display: flex;',
      '  flex-direction: column;',
      '  position: fixed;',
      '  left: 56px;',
      '  bottom: 16px;',
      '  z-index: 100001;',
      '  width: 280px;',
      '  max-height: 70vh;',
      '  overflow: auto;',
      '  background: #0e131a;',
      '  border: 1px solid #2a3340;',
      '  border-radius: 12px;',
      '  box-shadow: 0 12px 40px rgba(0,0,0,.5);',
      '  color: #e8edf5;',
      '  font-family: system-ui, -apple-system, Segoe UI, Roboto, sans-serif;',
      '  font-size: 12.5px;',
      '}',
      '.bss-toolkit-settings-panel[hidden] { display: none !important; }',
      '.bss-toolkit-settings-header {',
      '  display: flex;',
      '  align-items: center;',
      '  justify-content: space-between;',
      '  padding: 10px 12px 8px;',
      '  border-bottom: 1px solid #1f2937;',
      '}',
      '.bss-toolkit-settings-header h2 {',
      '  margin: 0;',
      '  font-size: 13px;',
      '  font-weight: 700;',
      '  letter-spacing: 0.02em;',
      '}',
      '.bss-toolkit-settings-close {',
      '  background: transparent;',
      '  border: none;',
      '  color: #9aa7b8;',
      '  cursor: pointer;',
      '  font-size: 18px;',
      '  line-height: 1;',
      '  padding: 0 4px;',
      '}',
      '.bss-toolkit-settings-close:hover { color: #e8edf5; }',
      '.bss-toolkit-settings-body { padding: 8px 12px 4px; }',
      '.bss-toolkit-settings-body h3 {',
      '  margin: 10px 0 6px;',
      '  font-size: 11px;',
      '  text-transform: uppercase;',
      '  letter-spacing: 0.06em;',
      '  color: #9aa7b8;',
      '}',
      '.bss-toolkit-settings-body h3:first-child { margin-top: 2px; }',
      '.bss-toolkit-settings-row {',
      '  display: flex;',
      '  align-items: center;',
      '  justify-content: space-between;',
      '  gap: 10px;',
      '  margin: 0 0 6px;',
      '  cursor: pointer;',
      '}',
      '.bss-toolkit-settings-row input[type="color"] {',
      '  width: 32px;',
      '  height: 22px;',
      '  padding: 0;',
      '  border: 1px solid #3a4a62;',
      '  border-radius: 4px;',
      '  background: #161b22;',
      '  cursor: pointer;',
      '}',
      '.bss-toolkit-settings-check {',
      '  display: flex;',
      '  align-items: center;',
      '  gap: 8px;',
      '  margin: 12px 0 8px;',
      '  cursor: pointer;',
      '}',
      '.bss-toolkit-settings-footer {',
      '  padding: 8px 12px 12px;',
      '  border-top: 1px solid #1f2937;',
      '}',
      '.bss-toolkit-settings-footer .bss-toolkit-btn { width: 100%; }',

      // -- Desktop toolkit parity: z-index + nav width (emotion classes may change) --
      '.css-ym7lu8 { z-index: 2; }',
      '.css-z1s6qn { z-index: 3; }',
      '.css-1jtoyp { z-index: 3; }',
      '#RCONLayout > nav > ul > li.css-1nxi32t > a {',
      '  width: 100vw;',
      '  max-width: 100%;',
      '}',
    ];
  },

  inject(): void {
    if (this.injected) return;
    this.injected = true;
    const style = document.createElement('style');
    style.setAttribute('data-bss-toolkit', '1');
    style.textContent = this.buildRules().join('\n');
    (document.head || document.documentElement).appendChild(style);
  },
};
